//
//  MenuData.swift
//  ForCuisine
//
//  Created by PHILIP LIM on 06/03/2020.
//  Copyright © 2020 Philip Lim. All rights reserved.
//

import Foundation

struct Dish : Identifiable {
    var id = UUID()
    var name: String
    var image: String
    var cuisine: String
    var course: String
    var ingredients: String
    var allergicContent: String
    var description: String
    var price: Int
    var story: String
    var restaurant: String
    var usdzModel: String?
    var frontpage: Bool
}

let dishesData = [
    Dish(name: NSLocalizedString("Kabab Saffron Rice", comment: ""),
         image: "kababbeef",
         cuisine: NSLocalizedString("Persian Cuisine", comment: ""),
         course: NSLocalizedString("Main", comment: ""),
         ingredients: NSLocalizedString("grated meat, basmati rice, saffron flower, onion, salt, pepper, sumac spice,", comment: ""),
         allergicContent:NSLocalizedString(" butter ", comment: ""),
         description: NSLocalizedString("Kubideh is a Persian's signature Kebab and the most famous of them all. It is made from ground lamb, beef or chicken mixed with grated onions. Koobideh refers to the style that meat was prepared, originally placed on a flat stone (precisely a black flat stone) and was smashed by wooden mallet. \n\nThe Kabab kubideh is then grilled on skewers, traditionally over hot coals, and is served with Chelo (basmati rice with oil, salt and saffron), accompanied by grilled tomatoes and onions. Sumac is usually served as a tableside garnishing spice.", comment: ""),
         price: 12,
         story: "(Chelo Kubideh)",
         restaurant: "Soraya Tea House",
         usdzModel: nil,
         frontpage: true),
    Dish(name: NSLocalizedString("Kabab Meal", comment: ""),
         image: "dishkababmeal",
         cuisine: NSLocalizedString("Persian Cuisine", comment: ""),
         course: NSLocalizedString("Main", comment: ""),
         ingredients: NSLocalizedString("ground chicken, lamb and beef, basmati rice, saffron flower", comment: ""),
         allergicContent: NSLocalizedString(" butter ", comment: ""),
         description: NSLocalizedString("Kabab Meal is in fact barbecued lamb, chicken or beef kebab dish. The main ingredients of Kabab-e Barg are fillets of beef tenderloin, lamb shank, onions, safron, olive oil and mild spices.", comment: ""),
         price: 16,
         story: "(Kabab Barg)",
         restaurant: "Soraya Tea House",
         usdzModel: nil,
         frontpage: false),
    Dish(name: NSLocalizedString("Chicken Kabab", comment: ""),
         image: "kababchickenjuje",
         cuisine: NSLocalizedString("Persian Cuisine", comment: ""),
         course: NSLocalizedString("Main", comment: ""),
         ingredients: NSLocalizedString("chicken meat, basmati rice, saffron flower, tomato, onion, salt, pepper, oliver oil, yogurt, lemon", comment: ""),
         allergicContent: NSLocalizedString(" butter ", comment: ""),
         description: NSLocalizedString("This Persian grilled saffron chicken is prepared by having the chicken pieces marinated in a saffron and yogurt based marinade and the chef usually having them marinated overnight to allow the chicken to absorb the flavors of saffron and lemon perfectly and becomes extra juicy and flavourful. It is served with Chelo (basmati rice with oil, lemon, tomato and saffron)", comment: ""),
         price: 12,
         story: "(Chelo Juje kabab)",
         restaurant: "Soraya Tea House",
         usdzModel: "chicken_meal",
         frontpage: false),
    Dish(name: NSLocalizedString("Barberry Rice Chicken Kabab", comment: ""),
         image: "kababchickenzereshk",
         cuisine: "Persian Cuisine",
         course:NSLocalizedString("Main", comment: ""),
         ingredients: "chicken meat, basmati rice, saffron flower, baberry, salt, pepper, sugar",
         allergicContent: "",
         description: "Zereshk Polo Morgh is one of the most famous dishes in Persian cuisine. It is cooked with full of wonderful flavors such as saffron, turmeric and barberry. The saffron rice is topped with delicious chicken strikes that makes a perfect balance between being simple enough and sumptuous enough for an elegant Persian feast. It is considered a very popular dish that would be served during formal and important festive ceremonies.",
         price: 9,
         story: "(Zereshk Polo Morgh)",
         restaurant: "Soraya Tea House",
         usdzModel: nil,
         frontpage: true),
    Dish(name: "Fava Beans Rice Chicken Kabab",
         image: "kababchickenbaghali",
         cuisine: "Persian Cuisine",
         course: NSLocalizedString("Main", comment: ""),
         ingredients: "chicken meat, basmati rice, saffron flower, fava beans, dill, salt, pepper",
         allergicContent: "",
         description: "Rice with fava beans with chicken. Baghali Polo basically refers to cooking of the fragrant basmati rice with fava beans and dill, which makes it fluffy and full of favour.  The cooked rice complements well with the tender, delicious steamed chicken breast meat. The original recipe for the food is prepared with lamb shank instead of chicken and it is called 'Baghali Polo ba Mahiche'.",
         price: 9,
         story: "(Baghali Polo Morgh)",
         restaurant: "Soraya Tea House",
         usdzModel: nil,
         frontpage: true),
    Dish(name: "Beef and Split Pea Stew",
         image: "beefstewgheymeh",
         cuisine: "Persian Cuisine",
         course: NSLocalizedString("Main", comment: ""),
         ingredients: "beef or lamb meat, basmati rice, split peas, saffron flower, tomato sauce, onion, potato or egg plant, salt, pepper",
         allergicContent: "",
         description: "The word Gheymeh comes from how the meat is cut into about one-inch small cubes. Traditionally Gheymeh is made with lamb or beef plus split pea cooked in slow stewing pot which is considered a very traditional way of popular Persian cooking.  The stew is then mixed with saffron potatoes and it is served with rice.",
         price: 9,
         story: "(Gheymeh)",
         restaurant: "Soraya Tea House",
         usdzModel: "pot_meal",
        frontpage: false),
    Dish(name: "Olivier Salad",
         image: "saladolivieh",
         cuisine: "Persian Cuisine",
         course: NSLocalizedString("Starter", comment: ""),
         ingredients: "chicken, potato, peas, pickle, mayonnaise, salt, pepper, dried lemon",
         allergicContent: "",
         description: "Salad Olivier is a well known dish all over the world, as popularly referred to as a traditional salad dish in Russian cuisine.  In Persian, they call it Salad Olivieh and the ingredients are rather different from the original recipe.  This salad is deliciously served fresh but taste even better when it has been refrigerated for a few hours or even overnight.",
         price: 9,
         story: "(Salad Olivieh)",
         restaurant: "Soraya Tea House",
         usdzModel: nil,
         frontpage: false),
    Dish(name: "Cream of Barley Soup",
         image: "soupejo",
         cuisine: "Persian Cuisine",
         course: NSLocalizedString("Starter", comment: ""),
         ingredients: "barley, tomato sauce, grated carrot, salt, pepper, dried barberries",
         allergicContent: "",
         description: "Cream of Barley Soup is a very wholesome and satisfying starter dish as it has the pearled barley (jo) goodness combined with fresh ingredients.",
         price: 9,
         story: "(Soup e Jo)",
         restaurant: "Soraya Tea House",
         usdzModel: nil,
         frontpage: false),
    Dish(name: "Cream of Mushroom Soup",
         image: "soupgharch",
         cuisine: "Persian Cuisine",
         course: NSLocalizedString("Starter", comment: ""),
         ingredients: "mushroom, grated carrot, salt, pepper, onion",
         allergicContent: " low fat milk, cream ",
         description: "Cream of Mushroom Soup is a Persian version of soup cooked in low fat milk.",
         price: 9,
         story: "(Soup e Gharch o Khameh)",
         restaurant: "Soraya Tea House",
         usdzModel: nil,
         frontpage: false),
    Dish(name: "Persian Tea with Saffron Rock Candy",
         image: "chai",
         cuisine: "Persian Cuisine",
         course: NSLocalizedString("Dessert", comment: ""),
         ingredients: "tea leaves, saffron, sugar",
         allergicContent: "",
         description: "The taste of the Chai can be quite overwhelming but in a good way as it is packed with spiced flavor which promote digestion as well as giving us as tea lovers a positive sense of well-being.It is usually served with a stick of rock candy which is made from saffron.",
         price: 9,
         story: "(Chai)",
         restaurant: "Soraya Tea House",
         usdzModel: nil,
         frontpage: false),
    Dish(name: "Baklava",
         image: "baghlava",
         cuisine: "Persian Cuisine",
         course: NSLocalizedString("Dessert", comment: ""),
         ingredients: "filo dough, honey, caster sugar",
         allergicContent: " butter, nuts - walnut, pistachio, almonds ",
         description: "Baklava is a rich, sweet pastry dessert made with layers of filo filled with chopped nuts, sweetened and held together with syrup, frosting or honey.",
         price: 9,
         story: "(Bāqlabā)",
         restaurant: "Soraya Tea House",
         usdzModel: nil,
         frontpage: false),
]
